// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zbw.Carrent.Shared;

#nullable disable

namespace Zbw.Carrent.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230904163053_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plz")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Car", b =>
                {
                    b.Property<int>("CarNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarNr"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.HasKey("CarNr");

                    b.HasIndex("BrandId")
                        .IsUnique();

                    b.HasIndex("CategoryId");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Categories.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<decimal>("DailyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Category");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Customer.Customer", b =>
                {
                    b.Property<int>("CustomerNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerNr"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerNr");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.RentalContract", b =>
                {
                    b.Property<int>("ContractNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractNr"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("ContractNr");

                    b.HasIndex("CarId");

                    b.HasIndex("ReservationId");

                    b.ToTable("RentalContract");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Reservation", b =>
                {
                    b.Property<int>("ReservationNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationNr"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReservationNr");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Categories.Economy", b =>
                {
                    b.HasBaseType("Zbw.Carrent.Customer.Domain.Categories.Category");

                    b.HasDiscriminator().HasValue("Economy");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Categories.Luxury", b =>
                {
                    b.HasBaseType("Zbw.Carrent.Customer.Domain.Categories.Category");

                    b.HasDiscriminator().HasValue("Luxury");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Categories.Midrange", b =>
                {
                    b.HasBaseType("Zbw.Carrent.Customer.Domain.Categories.Category");

                    b.HasDiscriminator().HasValue("Midrange");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Car", b =>
                {
                    b.HasOne("Zbw.Carrent.Customer.Domain.Brand", "Brand")
                        .WithOne("Car")
                        .HasForeignKey("Zbw.Carrent.Customer.Domain.Car", "BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zbw.Carrent.Customer.Domain.Categories.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zbw.Carrent.Customer.Domain.Model", "Model")
                        .WithOne("Car")
                        .HasForeignKey("Zbw.Carrent.Customer.Domain.Car", "ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Customer.Customer", b =>
                {
                    b.HasOne("Zbw.Carrent.Customer.Domain.Address", "Address")
                        .WithMany("Customer")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.RentalContract", b =>
                {
                    b.HasOne("Zbw.Carrent.Customer.Domain.Car", "Car")
                        .WithMany("RentalContracts")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zbw.Carrent.Customer.Domain.Reservation", "Reservation")
                        .WithMany("RentalContracts")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Reservation", b =>
                {
                    b.HasOne("Zbw.Carrent.Customer.Domain.Customer.Customer", "Customers")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Address", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Brand", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Car", b =>
                {
                    b.Navigation("RentalContracts");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Categories.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Customer.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Model", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();
                });

            modelBuilder.Entity("Zbw.Carrent.Customer.Domain.Reservation", b =>
                {
                    b.Navigation("RentalContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
